### PR TITLE
Lots of stuff

### PR DESCRIPTION
**Pull request by cvn**
Hi, @m1el

Thanks for making woscope available! I really like it.

I wanted to use it for a project and did a bunch of work to make it more modular and compatible with Safari/iOS. The project is now a browserify module, since it allowed for an easy path to inlining the shaders. There's a lot of changes, but most of it is organizational and build-related. I've tried to change as little of the logic as possible. Please look through the commits and feel free to ask me anything.

For the demo to work in Safari, you'll have to merge my woscope-music PR too (m1el/woscope-music#1). I think it's easiest if you do that before merging this PR.

There's 2 outstanding issues that I'm aware of:
1. The progress indicator does not scale with size of the canvas. I looked through the shader code and noticed some hardcoded 800s, but I don't know how to go about making the sizing relative. The scope itself scales nicely.
2. When using woscope in a single page app context, the console is spammed with OpenGL error messages if woscope is activated more than once e.g. `WebGL: INVALID_OPERATION: bindBuffer: object not from this context`. Woscope still works, but it'd be better without the errors. I may be able to look into this more in the future.

### CODE REVIEW

**Comment by m1el** [comment]
Hello, @cvn 

I appreciate the organization of this demo and cleaning up some of the mess in the code.

The pull-request changes are nice, 
however there are some things I'd like to be changed before merging:
- Separate the build commands with `&&` instead of `;`.
- `getText` function no longer has any meaning, just inline the `shaderDict` access
- for-of loops translate to _madness_, please replace them with `Array#forEach`
- jsHint complains about `CreateShader` looking like a constructor, it should probably be renamed to `createShader`

As for the issues - you can use https://github.com/m1el/woscope/issues to report them, 
and hope them to be fixed :)

**Comment by cvn** [comment]
Cool.

Which for-of loops are you talking about? The ones I see are in the demo, and look harmless. I agree with the rest of the changes (including the woscope-music ones) and I will implement them soon.

**Comment by m1el** [comment]
> Which for-of loops are you talking about?

I'm talking about all loops in form `for (let xxx of yyy)`, e.g.

https://github.com/cvn/woscope/blob/714dd6e0/demo/index.js#L33-L35

gets browserify-ed to

https://github.com/cvn/woscope/blob/714dd6e0/dist/demo.js#L30-L53

Anyway, this change does not really affect the source code quality, it only affects build source code readability.

**Comment by cvn** [comment]
Hi @m1el I updated the PR with changes from your feedback. Let me know if there's anything else. I also added a `.travis.yml` file, so you could add the repo to [Travis](https://travis-ci.com/) if you'd like.

**Comment by cvn** [comment]
Great! Don't forget to update the `gh-pages` branch.

**Comment by m1el** [comment]
Yea, thanks for the fixes, I'll update the gh-pages branch soon.

**Pull request merged**
